SELECT DISTINCT E.SEQENCARTE COD_ENCARTE, 
       NVL(M.NROEMPRESA,G.NROEMPRESA) LOJA, 
       C.CATEGORIAN1,
       C.CATEGORIAN2,
       E.SEQPRODUTO PLU,
       /*CASE 
         WHEN COUNT(*) OVER (PARTITION BY E.SEQPRODUTO, NVL(M.NROEMPRESA,G.NROEMPRESA)) > 1 
         THEN '*' 
         ELSE NULL 
       END AS OBS,*/
       CASE 
         WHEN MIN(E.PRECOPROMOCIONAL) OVER (PARTITION BY E.SEQPRODUTO, NVL(M.NROEMPRESA,G.NROEMPRESA)) 
            <> MAX(E.PRECOPROMOCIONAL) OVER (PARTITION BY E.SEQPRODUTO, NVL(M.NROEMPRESA,G.NROEMPRESA))
         THEN '*'
         ELSE NULL
       END AS OBS,
       P.DESCCOMPLETA DESCRICAO,
       E.PRECOATUAL DE,
       E.PRECOPROMOCIONAL POR,
       TO_CHAR(E.DTAINICIO, 'DD/MM/YYYY') DATA_INICIO,
       TO_CHAR(E.DTAFIM, 'DD/MM/YYYY') DATA_FIM,
       NULL DATA_HORA,
       E.descricao DESC_ACAO

  FROM NAGV_ENCARTE_V3 E INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = E.SEQPRODUTO 
                         INNER JOIN DIM_CATEGORIA@CONSINCODW C ON C.SEQFAMILIA = E.SEQFAMILIA
                          LEFT JOIN NAGV_AGRUP_EMP_ENCARTE G ON G.NROAGRUPAMENTO = E.NROAGRUPAMENTO AND E.TIPO_GRP = G.TIPO_GRP AND NROEMPRESA < 100
                          LEFT JOIN MRL_ENCARTEEMP M ON M.SEQENCARTE = E.SEQENCARTE AND E.TIPO_GRP IS NULL
                         
 WHERE E.SEQENCARTE IN (#LT1)
   AND NVL(M.NROEMPRESA,G.NROEMPRESA) IN (#LS1)
   AND E.PRECOPROMOCIONAL > 0
   AND EXISTS (SELECT 1
                 FROM CONSINCO.MRL_ENCARTEPRODUTO A
                WHERE A.SEQENCARTE = E.SEQENCARTE
                  AND A.SEQPRODUTO = E.SEQPRODUTO
                  AND A.NROPAGINA = E.PAGINA
                  AND A.SEQORDEM = E.SEQORDEM)
               
 ORDER BY DESCCOMPLETA, NVL(M.NROEMPRESA,G.NROEMPRESA), E.SEQENCARTE;
 
