CREATE OR REPLACE VIEW CONSINCO.MRLV_PROMOCAOESPECIAL AS

-- VIEW ALTERADA POR GIULIANO EM 24/06/2024
-- VIEW SERÁ UTILIZADA PARA RETORNAR AO GRID OS PREÇOS DO MEU NAGUMO
-- ESSA VIEW FAZ JOIN CCOM A MRLV_BASEETIQUETAPROD QUANDO SELECIONADO A OPÇÃO "Promoc. Especial por codigos específicos" NA EMISSÃO DE ETIQUETAS

-- SELECT ORIGINAL:
/*
SELECT A.SEQPRODUTO,
       A.QTDEMBALAGEM,
       A.NROEMPRESA,
       A.CODACESSOESPECIAL,
       A.VLRPRECOPROMOC,
       A.QTDESOLICITADA,
       A.DTAINICIO,
       A.DTAFIM,
       NVL(A.INDEMIETIQUETA,'N') AS INDEMIETIQUETA,
       A.SEQPROMOCESPECIAL,
       A.MOTIVOACAOPROMOC
FROM MRL_PROMOCESPECIALHIST A
WHERE A.STATUS = 'A';*/

-- NOVO:

SELECT DISTINCT * FROM (

SELECT /*+OPTIMIZER_FEATURES_ENABLE('11.2.0.4')*/  
       SF.SEQPRODUTO,
       XE.NROEMPRESA,
       1 QTDEMBALAGEM,
       'N' INDEMIETIQUETA,
       1 QTDETIQUETA,
       TRUNC(SYSDATE) DTAINICIO,
       
       777 CODACESSOESPECIAL,
       777 SEQPROMOCESPECIAL,
       0 VLRPRECOPROMOC,
       1 QTDESOLICITADA,
       NULL DTAFIM,
       NULL MOTIVOACAOPROMOC


-- COMEÇA O TRATAMENTO PARA RETORNO DOS PRODUTOS DENTRO DOS ENCARTES (MEU NAGUMO)
-- BUSCA SIMILARES

  FROM MRL_ENCARTE X INNER JOIN MRL_ENCARTEPRODUTO XI      ON XI.SEQENCARTE = X.SEQENCARTE
                     INNER JOIN CONSINCO.MRL_ENCARTEEMP XE ON XE.SEQENCARTE = X.SEQENCARTE
                     INNER JOIN CONSINCO.MRL_ENCARTEPRODUTOPRECO PP ON PP.SEQENCARTE = X.SEQENCARTE AND PP.SEQPRODUTO = XI.SEQPRODUTO
                     INNER JOIN MAP_PRODSIMILAR S          ON S.SEQPRODUTO  = XI.SEQPRODUTO
                     INNER JOIN MAP_PRODSIMILAR SF         ON SF.SEQSIMILARIDADE = S.SEQSIMILARIDADE

 WHERE 1=1

   AND X.SEQGRUPOPROMOC NOT IN (7,9)      -- RETIRA PROPZ / VALIDADE
   AND NVL(PP.PRECOCARTAO,0) > 0          -- APENAS OS QUE POSSUEM PRECO MEU NAGUMO
   AND (NVL(XI.DTAVIGENCIAFIM,DTAFIM)        = TRUNC(SYSDATE) - 1 -- RETORNANDO AS SAIDAS DO DIA ANTERIOR
   -- RETIRADO SOLIC RAQUEL POIS ESTA ANTECIPANDO
    OR  NVL(XI.DTAVIGENCIAINI,X.DTAINICIO)   = TRUNC(SYSDATE))    -- (OU) RETORNA OS QUE INICIAREM HOJE

-- BUSCA FAMILIARES

    UNION        
    
SELECT /*+OPTIMIZER_FEATURES_ENABLE('11.2.0.4')*/ 
       PF.SEQPRODUTO,
       XE.NROEMPRESA,
       1 QTDEMBALAGEM,
       'N' INDEMIETIQUETA,
       1 QTDETIQUETA,
       TRUNC(SYSDATE) DTAINICIO,
       
       777 CODACESSOESPECIAL,
       777 SEQPROMOCESPECIAL,
       0 VLRPRECOPROMOC,
       1 QTDESOLICITADA,
       NULL DTAFIM,
       NULL MOTIVOACAOPROMOC
       
 FROM MRL_ENCARTE X INNER JOIN MRL_ENCARTEPRODUTO XI      ON XI.SEQENCARTE = X.SEQENCARTE
                    INNER JOIN CONSINCO.MRL_ENCARTEEMP XE ON XE.SEQENCARTE = X.SEQENCARTE
                    INNER JOIN CONSINCO.MRL_ENCARTEPRODUTOPRECO PP ON PP.SEQENCARTE = X.SEQENCARTE AND PP.SEQPRODUTO = XI.SEQPRODUTO
                    INNER JOIN MAP_PRODUTO P              ON P.SEQPRODUTO  = XI.SEQPRODUTO
                    INNER JOIN MAP_PRODUTO PF             ON PF.SEQFAMILIA = P.SEQFAMILIA

 WHERE 2=2

   AND X.SEQGRUPOPROMOC NOT IN (7,9)      -- RETIRA PROPZ / VALIDADE
   AND NVL(PP.PRECOCARTAO,0) > 0          -- APENAS OS QUE POSSUEM PRECO MEU NAGUMO
   AND (NVL(XI.DTAVIGENCIAFIM,DTAFIM)        = TRUNC(SYSDATE) - 1 -- RETORNANDO AS SAIDAS DO DIA ANTERIOR
   -- RETIRADO SOLIC RAQUEL POIS ESTA ANTECIPANDO
    OR  NVL(XI.DTAVIGENCIAINI,X.DTAINICIO)   = TRUNC(SYSDATE))

)
