CREATE OR REPLACE FUNCTION NAGF_BUSCASEQREC (psCodigo NUMBER)

  RETURN NUMBER IS

  seqRec NUMBER(10);

  BEGIN

 SELECT SEQITEM
   INTO seqRec
   FROM RF_TABAUXPCITENS X WHERE X.SEQTABAUX = 9 AND X.CODIGO = psCodigo;


  RETURN seqRec;

  END;
