CREATE OR REPLACE FUNCTION NAGF_BUSCADUN (pSeqproduto  NUMBER,
                                          pQtdEmbalagem NUMBER)
  RETURN VARCHAR2 IS
  vsDUN VARCHAR2(400);

BEGIN  

SELECT TO_CHAR(MAX(CODACESSO))
  INTO vsDUN
  FROM CONSINCO.MAP_PRODCODIGO XX

 WHERE XX.SEQPRODUTO = pSeqproduto
   AND XX.QTDEMBALAGEM = pQtdEmbalagem
   AND XX.TIPCODIGO = 'D'
   AND XX.INDUTILVENDA = 'S';

   RETURN vsDUN;
   
   END;

