CREATE OR REPLACE FUNCTION NAGF_MENOR_DIA_FIXO (pnSeqLoteModelo IN NUMBER)
 
RETURN NUMBER IS
  psDiaFixo NUMBER;

BEGIN
  SELECT MIN(DIA_FIXO)
    INTO psDiaFixo
   FROM NAGT_CONTROLELOTECOMPRA X
  WHERE X.SEQLOTEMODELO = pnSeqLoteModelo
    AND DIA_FIXO >= TO_CHAR(SYSDATE, 'DD');
  
  RETURN psDiaFixo;
  
END;
