CREATE OR REPLACE FUNCTION NAGF_BUSCA_dPrevEntrega_NT (psNroEmpresa NUMBER) 

  RETURN DATE IS
  vDPrevEntrega DATE;
  
  BEGIN

    SELECT MAX(TRUNC(SYSDATE) + NVL(PADRAO,0))
      INTO vDPrevEntrega
      FROM MAX_EMPRESANOTATECNICADET A INNER JOIN MAX_EMPRESANOTATECNICA B ON A.SEQNOTATECNICA = B.SEQNOTATECNICA
     WHERE DESCRICAO = 'dPrevEntrega'
       AND ORIGEM = 1
       AND B.NROEMPRESA = psNroEmpresa;
  
  RETURN vDPrevEntrega;
  END;
