CREATE OR REPLACE FUNCTION NAGF_BUSCA_SEQPRODUTO (psCodigo NUMBER)

   RETURN NUMBER RESULT_CACHE IS
    psReturn NUMBER(30);
    
   BEGIN
     
   SELECT NVL(MAX(SEQPRODUTO),0) 
     INTO psReturn
     FROM DIM_PRODUTOCODIGO X
    WHERE X.TIPCODIGO IN ('E','D','B','I') 
      AND REGEXP_LIKE(X.CODACESSO, '^[0-9]+$')
      AND psCodigo = CASE WHEN LENGTH(psCODIGO) < 11 THEN X.SEQPRODUTO ELSE TO_NUMBER(X.CODACESSO) END;
    
   RETURN psReturn;
   
   
   END;
