CREATE OR REPLACE VIEW NAGT_CRM_PRODEMPRESA AS

SELECT S.NROEMPRESA LOJA, S.SEQPRODUTO PLU, P.DESCCOMPLETA,
       LISTAGG(CODACESSO, ', ') WITHIN GROUP (ORDER BY S.SEQPRODUTO) EAN,
       DECODE(S.STATUSVENDA, 'A', 'ATIVO', 'I', 'INATIVO') STATUS_VENDA,
       DECODE(P.INDINTEGRAECOMMERCE, 'S','Sim', 'N', 'Não') INTEGRA_ECOMM
       
  FROM MRL_PRODEMPSEG S INNER JOIN MAX_EMPRESASEG I ON I.NROEMPRESA = S.NROEMPRESA AND I.NROSEGMENTO IN (5,8)
                        INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = S.SEQPRODUTO
                         LEFT JOIN MAP_PRODCODIGO C ON C.SEQPRODUTO = S.SEQPRODUTO AND TIPCODIGO = 'E' AND INDUTILVENDA = 'S' AND C.QTDEMBALAGEM = S.QTDEMBALAGEM
                        
 WHERE 1=1
   AND I.STATUS = 'A'
   AND S.STATUSVENDA = 'A'
   AND S.QTDEMBALAGEM = 1
   
   GROUP BY S.NROEMPRESA, S.SEQPRODUTO, S.STATUSVENDA, P.INDINTEGRAECOMMERCE, DESCCOMPLETA
