CREATE OR REPLACE VIEW NAGT_NF_RELAC_REMESSA_V2 AS

SELECT B.SEQNF SEQNF_1, C.SEQNF SEQNF_2
  FROM MLF_NFCOMPRAREMESSARELAC X INNER JOIN MLF_NOTAFISCAL B ON B.SEQAUXNOTAFISCAL = X.SEQIDENTIFICAORIGEM
                                  INNER JOIN MLF_NOTAFISCAL C ON C.SEQAUXNOTAFISCAL = X.SEQIDENTIFICARELACIONADO
WHERE 1=1 AND X.TIPORELACIONADO = 'M'
