CREATE OR REPLACE TRIGGER NAGTR_INATIVA_MSG_CUSTOM

AFTER INSERT OR UPDATE ON GE_APLICACAOMENSAGEM
  
BEGIN
  FOR t IN (SELECT SEQAPLICACAOMENSAGEM FROM GE_APLICACAOMENSAGEM X WHERE X.STATUS = 'A')
    LOOP
  UPDATE GE_APLICACAOMENSAGEM X SET X.STATUS = 'I' WHERE X.SEQAPLICACAOMENSAGEM = t.SEQAPLICACAOMENSAGEM;
    END LOOP;
END;
