CREATE OR REPLACE VIEW NAGV_BASE_CAD_MOVTO AS
SELECT DISTINCT A.SEQPRODUTO PLU, DESCCOMPLETA DESCRICAO, COMPRADOR,
       MAX(DTAULTCOMPRA) DTA_ULT_COMPRA,
       MAX(C.DTAHORINCLUSAO) DTA_INCLUSAO,
       DECODE(NVL(MIN(F.STATUSCOMPRA), 'I'), 'I','INATIVO','A','ATIVO','SUSPENSO') STATUSCOMPRA,
       DECODE(NVL(MIN(A.STATUSVENDA),  'I'), 'I','INATIVO','A','ATIVO','SUSPENSO') STATUSVENDA,
       CASE WHEN (SELECT MAX(CD.DTAULTENTRADA) FROM MRL_PRODUTOEMPRESA CD WHERE CD.SEQPRODUTO = A.SEQPRODUTO AND CD.NROEMPRESA >= 500) IS NULL THEN 'SEM ENTRADA NO CD'
            ELSE TO_CHAR((SELECT MAX(CD.DTAULTENTRADA) FROM MRL_PRODUTOEMPRESA CD WHERE CD.SEQPRODUTO = A.SEQPRODUTO AND CD.NROEMPRESA >= 500), 'DD/MM/YYYY') END DTA_ULT_ENT_CD,
       CASE WHEN EXISTS (SELECT 1
                           FROM MSU_PSITEMRECEBER J INNER JOIN MSU_PEDIDOSUPRIM L ON L.NROPEDIDOSUPRIM = J.NROPEDIDOSUPRIM AND L.NROEMPRESA = J.NROEMPRESA
                          WHERE J.QTDSOLICITADA - (J.QTDTOTRECEBIDA + ABS(J.QTDTOTCANCELADA) + ABS(J.QTDTOTTRANSITO)) > 0
                            AND L.SITUACAOPED != 'C'
                            AND DTAEMISSAO > SYSDATE - 100
                            AND J.SEQPRODUTO = A.SEQPRODUTO) THEN 'EXISTE PED PENDENTE' ELSE NULL END PED_PENDENTE,
       --SUM(F.ESTQLOJA) + SUM(F.ESTQDEPOSITO) ESTOQUE,
       DECODE(MAX(F.DTAULTVENDA), NULL, 'SEM VENDA', ROUND(SYSDATE - MAX(F.DTAULTVENDA),0) ) DIAS_SEM_VENDA
    --   QL.CATEGORIA_NIVEL_1, QL.CATEGORIA_NIVEL_2, QL.CATEGORIA_NIVEL_3, QL.CATEGORIA_NIVEL_4, QL.CATEGORIA_NIVEL_5

  FROM MRL_PRODEMPSEG A --LEFT JOIN  MAP_PRODCODIGO B ON A.SEQPRODUTO = B.SEQPRODUTO AND B.TIPCODIGO = 'E'
                        INNER JOIN MAP_PRODUTO C ON C.SEQPRODUTO = A.SEQPRODUTO
                        INNER JOIN MAP_FAMDIVISAO D ON D.SEQFAMILIA = C.SEQFAMILIA
                        INNER JOIN MAX_COMPRADOR E ON E.SEQCOMPRADOR = D.SEQCOMPRADOR
                        --LEFT JOIN  QLV_CATEGORIA@CONSINCODW QL ON QL.SEQFAMILIA = C.SEQFAMILIA
                        INNER JOIN MRL_PRODUTOEMPRESA F ON F.NROEMPRESA = A.NROEMPRESA AND F.SEQPRODUTO = A.SEQPRODUTO
 WHERE EXISTS (SELECT 1 FROM MAX_EMPRESA X WHERE X.NROEMPRESA = A.NROEMPRESA AND X.NROSEGMENTOPRINC = A.NROSEGMENTO)

   AND C.DTAHORINCLUSAO BETWEEN SYSDATE - (6*30) AND SYSDATE

 GROUP BY A.SEQPRODUTO,  DESCCOMPLETA, COMPRADOR
         -- QL.CATEGORIA_NIVEL_1, QL.CATEGORIA_NIVEL_2, QL.CATEGORIA_NIVEL_3, QL.CATEGORIA_NIVEL_4, QL.CATEGORIA_NIVEL_5

 ORDER BY 3,1
;
