CREATE OR REPLACE VIEW NAGV_PROD_EXCLUIDO_CAMP AS
SELECT A.TIPO, A.SEQPRODUTO, P.DESCCOMPLETA, B.CODACESSO CODIGO, B.TIPCODIGO
  FROM MAP_PRODDESCESP A INNER JOIN MAP_PRODCODIGO B ON A.SEQPRODUTO = B.SEQPRODUTO
                         INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = A.SEQPRODUTO
 WHERE A.TIPO = 'Item Excluido de Campanhas'
   AND B.TIPCODIGO != 'F';
