CREATE OR REPLACE VIEW NAGV_APURACAO_SELLOUT_VALIDADE AS
SELECT /*+OPTIMIZER_FEATURES_ENABLE('11.2.0.4')*/
       MAX(A.QTDESOLICITADA)     QTD_SOLIC,
       NVL(SUM(B.QTDOPERACAO),0) QTD_VENDIDA,
       MAX(DTAFIM)               DTA_VENCTO,
       B.NROEMPRESA, B.SEQPRODUTO
  FROM FATO_VENDA  B INNER JOIN MRL_PROMOCESPECIALHIST A ON B.SEQPRODUTO = A.SEQPRODUTO
                                                         AND TRUNC(SYSDATE) BETWEEN DTAINICIO AND DTAFIM
                                                         AND B.NROEMPRESA = A.NROEMPRESA
                                                         AND B.DTAOPERACAO BETWEEN DTAINICIO AND DTAFIM
                                                         AND A.CODACESSOESPECIAL = B.CODPRODUTO

 WHERE 1=1
 GROUP BY B.NROEMPRESA, B.SEQPRODUTO;
