CREATE OR REPLACE VIEW NAGV_BAKESHOP_PJ_SF AS
SELECT /*+OPTIMIZER_FEATURES_ENABLE('19.1.0')*/
       --DISTINCT Z.CODACESSO COD_PRODUTO,
    DISTINCT   NVL(TRIM(Fbuscaeanprodutonag(p.seqproduto)),Z.SEQPRODUTO ) COD_PRODUTO,
       Z.SEQPRODUTO PLU,
       DESCCOMPLETA,
       F.CODNBMSH COD_NCM,
       F.CODCEST COD_CEST,
       NVL(UC.CFOPESTADO,(SELECT CGO.CFOPESTADO FROM MAX_CODGERALOPER CGO WHERE CGO.CODGERALOPER = 610)) CFOP,
       U.SITUACAONF CST_ICMS, F.SITUACAONFPISSAI CST_PIS, F.SITUACAONFCOFINSSAI CST_COFINS,
       F.SITUACAONFIPISAI CST_IPI, NULL CST_ISS, U.PERALIQUOTA ALIQ_ICMS, U.PERISENTO PERREDUCAO,
       CASE WHEN F.SITUACAONFPISSAI = '01' THEN 1.65 ELSE 0 END ALIQ_PIS,
       CASE WHEN F.SITUACAONFCOFINSSAI = '01' THEN 7.60 ELSE 0 END ALIQ_COFINS,
       NVL(F.PERALIQUOTAIPI,0) ALIQ_IPI,
       NVL(NULLIF(PRECOVALIDPROMOC,0), PRECOVALIDNORMAL) PRECO_VDA,
       COALESCE(CATEGORIAN3, CATEGORIAN2, CATEGORIAN1) CATEGORIA,

       /* */

       CASE WHEN U.SITUACAONF = '060' THEN NVL(ESP_FCALCVALORICMSULTENTRADA(Z.SEQPRODUTO, S.NROEMPRESA,'B',  TRUNC(SYSDATE),810), 0) ELSE 0 END       vBSCTRet,
       CASE WHEN U.SITUACAONF = '060' THEN NVL(ESP_FCALCVALORICMSULTENTRADA(Z.SEQPRODUTO, S.NROEMPRESA,'AS' ,TRUNC(SYSDATE),810), 0) ELSE 0 END       pST,
       CASE WHEN U.SITUACAONF = '060' THEN NVL(ESP_FCALCVALORICMSULTENTRADA(Z.SEQPRODUTO, S.NROEMPRESA,'V',  TRUNC(SYSDATE),810), 0) ELSE 0 END       vICMSSubstituto,
       CASE WHEN U.SITUACAONF = '060' THEN NVL(ESP_FCALCVALORICMSULTENTRADA(Z.SEQPRODUTO, S.NROEMPRESA,'V',  TRUNC(SYSDATE),810), 0) ELSE 0 END       vICMSSTRet,
       CASE WHEN U.SITUACAONF = '060' THEN NVL(ESP_FCALCVALORICMSULTENTRADA(Z.SEQPRODUTO, S.NROEMPRESA,'BF', TRUNC(SYSDATE),810), 0) ELSE 0 END       vBCFCPRet,
       CASE WHEN U.SITUACAONF = '060' THEN NVL(ESP_FCALCVALORICMSULTENTRADA(Z.SEQPRODUTO, S.NROEMPRESA,'AF', TRUNC(SYSDATE),810), 0) ELSE 0 END       pFCPSTRet,
       CASE WHEN U.SITUACAONF = '060' THEN NVL(ESP_FCALCVALORICMSULTENTRADA(Z.SEQPRODUTO, S.NROEMPRESA,'VF', TRUNC(SYSDATE),810), 0) ELSE 0 END       vFCPSTRet,
       CASE WHEN U.SITUACAONF = '060' THEN  nvl(U.PERREDBCICMSEFET,0) ELSE 0 END                                                                             pRedBCEfet,
       CASE WHEN U.SITUACAONF = '060' THEN (SELECT ALIQPADRAOICMS FROM MAP_FAMALIQPADRAOUF WHERE SEQFAMILIA = P.SEQFAMILIA AND UF = 'SP') ELSE 0 END  pICMSEfet,
      
     /* Reforma */
       
       /* CBS */     RF.CENARIOCBS, RF.PERALIQCBS, RF.PERALIQREDCBS, RF.PERALIQCCREDPRESCBS, RF.PERALIQREDCCREDPRESCBS, RF.CSTCBS, RF.CCLASSTRIBCBS, RF.CCREDPRESCBS,
       /* IBS */     RF.CENARIOIBSUF, RF.PERALIQIBSUF, RF.PERALIQREDIBSUF, RF.PERALIQCCREDPRESIBSUF, RF.PERALIQREDCCREDPRESIBSUF, RF.CSTIBSUF, RF.CCLASSTRIBIBSUF, RF.CCREDPRESIBSUF,
       /* IBS MUN*/  RF.CENARIOIBSMUN, RF.PERALIQIBSMUN, RF.PERALIQREDIBSMUN, RF.CSTIBSMUN, RF.CCLASSTRIBIBSMUN,
       /* IS */      RF.CENARIOIS, RF.PERALIQIS, RF.PERALIQREDIS, RF.CSTIS, RF.CCLASSTRIBIS,
       
       S.NROEMPRESA

  FROM MAP_PRODCODIGO Z INNER JOIN MAP_PRODUTO P       ON P.SEQPRODUTO = Z.SEQPRODUTO AND Z.TIPCODIGO IN ('E','B')
                        INNER JOIN MAP_FAMILIA F       ON F.SEQFAMILIA = P.SEQFAMILIA
                        INNER JOIN MAP_FAMDIVISAO D    ON D.SEQFAMILIA = F.SEQFAMILIA
                        INNER JOIN MAP_TRIBUTACAOUF U  ON U.NROTRIBUTACAO = D.NROTRIBUTACAO
                         LEFT JOIN MAX_CODGERALCFOP UC ON UC.NROTRIBUTACAO = D.NROTRIBUTACAO AND UC.CODGERALOPER = 610
                        INNER JOIN MRL_PRODEMPSEG S    ON S.SEQPRODUTO = Z.SEQPRODUTO AND NROSEGMENTO = 10 AND  S.QTDEMBALAGEM = 1 and s.statusvenda = 'A'
                        INNER JOIN DIM_CATEGORIA@CONSINCODW CT ON CT.SEQFAMILIA = P.SEQFAMILIA
                        --INNER JOIN MAX_COMPRADOR CP    ON  CP.SEQCOMPRADOR = D.SEQCOMPRADOR
                        -- Reforma Tributaria
                         LEFT JOIN PDV_CENARIOPRODUTO RF ON RF.SEQPRODUTO = P.SEQPRODUTO AND RF.CIDADE = 'SAO PAULO'

WHERE 1=1

  AND U.UFEMPRESA          = 'SP'
  AND U.UFCLIENTEFORNEC    = 'SP'
  AND U.NROREGTRIBUTACAO   = 0
  AND U.TIPTRIBUTACAO      = 'SN'

  ORDER BY 3
;
