CREATE OR REPLACE VIEW NAGV_BUSCA_CCT_PROD_NCM AS
SELECT C.SEQCENARIO CENARIO, PD.SEQPRODUTO PLU, PD.DESCCOMPLETA, PD.SEQFAMILIA COD_FAMILIA, CI.IDENTIFICADOR IDENT_CCT,
      (SELECT LISTAGG(CODGERALOPER, ', ') WITHIN GROUP (ORDER BY CODGERALOPER) FROM MAX_CODGERALOPER CGO WHERE CGO.CODGERALOPER = CI.VALOR AND CI.IDENTIFICADOR = 'CGO') CGO, NCM,
      X.CENARIOCBS,
      X.PERALIQCBS,
      X.PERALIQREDCBS,
      X.PERALIQCCREDPRESCBS,
      X.PERALIQREDCCREDPRESCBS,
      X.CSTCBS,
      X.CCLASSTRIBCBS,
      X.CCREDPRESCBS,
      X.CENARIOIBSUF,
      X.PERALIQIBSUF,
      X.PERALIQREDIBSUF,
      X.PERALIQCCREDPRESIBSUF,
      X.PERALIQREDCCREDPRESIBSUF,
      X.CSTIBSUF,
      X.CCLASSTRIBIBSUF,
      X.CCREDPRESIBSUF,
      X.CENARIOIBSMUN,
      X.PERALIQIBSMUN,
      X.PERALIQREDIBSMUN,
      X.CSTIBSMUN,
      X.CCLASSTRIBIBSMUN,
      X.CENARIOIS,
      X.PERALIQIS,
      X.PERALIQREDIS,
      X.CSTIS,
      X.CCLASSTRIBIS

  FROM CCT_CENARIO C INNER JOIN CCT_CENARIOCONDICAOITEM CI ON CI.SEQCENARIO = C.SEQCENARIO
                     INNER JOIN MAP_FAMILIA F ON (CI.IDENTIFICADOR = 'NCM' AND CI.VALOR = TO_CHAR(F.CODNBMSH))
                     INNER JOIN MAP_PRODUTO PD ON PD.SEQFAMILIA = F.SEQFAMILIA AND CI.IDENTIFICADOR IN ('NCM')
                     INNER JOIN NAGV_BUSCA_CCT X ON X.CENARIOCBS = C.SEQCENARIO AND X.SEQPRODUTO = PD.SEQPRODUTO

 WHERE 1=1;
