CREATE OR REPLACE VIEW NAGV_PROD_ACELERADORES AS
  
SELECT A.CODIGO COD_AT, A.TIPO ATRIBUTO, A.SEQPRODUTO CODPRODUTO, P.DESCCOMPLETA, B.CODACESSO CODIGO, B.TIPCODIGO, DESCRICAO DESC_ATRIBUTO
  FROM MAP_PRODDESCESP A INNER JOIN MAP_PRODCODIGO B ON A.SEQPRODUTO = B.SEQPRODUTO
                         INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = A.SEQPRODUTO
                         INNER JOIN MAP_DESCESP E ON E.TIPO = A.TIPO AND A.CODIGO = E.CODIGO
 WHERE UPPER(A.TIPO) LIKE '%ACELERADOR%'
   AND B.TIPCODIGO != 'F'
   AND NOT EXISTS (SELECT 1 FROM MAP_PRODDESCESP EX WHERE EX.SEQPRODUTO = A.SEQPRODUTO AND UPPER(EX.TIPO) LIKE '%EXCLU_DO%');
