CREATE OR REPLACE VIEW NAGV_CRM_PESSOA_EXT AS
SELECT SEQPESSOA IDUNICO,
       CASE WHEN X.FISICAJURIDICA = 'F' THEN LPAD(NROCGCCPF,9,0)||LPAD(DIGCGCCPF,2,0)
         ELSE LPAD(NROCGCCPF,12,0)||LPAD(DIGCGCCPF,2,0) END IDPESSOA,
       REPLACE(X.NOMERAZAO, ';', ' ') TXTNOMECOMPLETO,
       CASE WHEN C.ESTADOCIVIL LIKE '%NULO%' THEN NULL ELSE C.ESTADOCIVIL END TXTESTADOCIVIL,
       DECODE(X.SEXO, 'M', 'MASCULINO','F','FEMININO') TXTSEXO,
       TO_CHAR(X.DTANASCFUND,'YYYY-MM-DD"T"HH24:MI:SS') DATNASCIMENTO,
      (SELECT MIN(DTAMOVIMENTO) FROM MFL_DOCTOFISCAL XX WHERE XX.SEQPESSOA = X.SEQPESSOA AND XX.STATUSDF != 'C') DTAPRIMCOMPRA,
      (SELECT MAX(DTAMOVIMENTO) FROM MFL_DOCTOFISCAL XX WHERE XX.SEQPESSOA = X.SEQPESSOA AND XX.STATUSDF != 'C') DTAULTCOMPRA,
       DTAALTERACAO DATATUALIZACAOCADASTRO,
       TO_CHAR(NVL(X.DTAINCLUSAO,DTAHORAINTEGRACAO),'YYYY-MM-DD"T"HH24:MI:SS') DATCADASTRO,
       CASE WHEN LENGTH(X.FONENRO1) = 11 THEN X.FONENRO1 ELSE X.FONEDDD1||X.FONENRO1 END NUMCEL1,
       -- X.FONEDDD1||X.FONENRO1 NUMCEL1,
       CASE WHEN LENGTH(X.FONENRO2) = 11 THEN X.FONENRO2 ELSE X.FONEDDD2||X.FONENRO2 END NUMCEL2,
       --X.FONEDDD2||X.FONENRO2 NUMCEL2,
       X.FAXNRO NUMTELFIXO,
       NULL NUMTELCOMERCIAL,
       X.EMAIL TXTEMAIL,
       X.CEP TXTCEP,
       REPLACE(X.LOGRADOURO, ';',' ') || CASE WHEN X.NROLOGRADOURO = '0' OR X.CEP = '0' THEN NULL ELSE ' - '||X.NROLOGRADOURO END TXTENDERECO,
       X.BAIRRO TXTBAIRRO,
       X.CIDADE TXTCIDADE,
       X.UF ESTADO,
       CASE WHEN X.USUINCLUSAO IN ('AFV','ECOMM') THEN 'ECOMMERCE'
            WHEN X.USUINCLUSAO = 'APICADASTRO' THEN 'APP'
            ELSE 'PDV' END CANAL_CADASTRO

  FROM GE_PESSOA X LEFT JOIN DIM_CLIENTE C ON C.SEQCLIENTE = X.SEQPESSOA
 WHERE 1 = 1
   --AND X.SEQPESSOA > 999
   AND NROCGCCPF IS NOT NULL
   --AND NROCGCCPF NOT IN ('00000000000000','000000000000','99999999999','000999999999')
   AND NVL(X.FISICAJURIDICA, 'F') = 'F'
   /*AND X.STATUS = 'A'*/
;
