-- Criando a Tabela

CREATE TABLE NAGT_BASE_CGO_FINALIDADE (FINALIDADE VARCHAR2(777), TIPO VARCHAR2(1), CGO_LIST VARCHAR2(4000));

SELECT * FROM NAGT_BASE_CGO_FINALIDADE;

-- Criando a View que quebra o CGO_LIST por linha para ser utilizado nos exists/in

CREATE OR REPLACE VIEW NAGV_BASE_CGO_FINALIDADE AS

SELECT X.TIPO, TRIM(REGEXP_SUBSTR(CGO_LIST, '[^,]+', 1, LEVEL)) CGO_LIST
  FROM NAGT_BASE_CGO_FINALIDADE X
 WHERE 1=1
 
CONNECT BY LEVEL <= REGEXP_COUNT(CGO_LIST, ',') + 1

   AND PRIOR FINALIDADE = FINALIDADE
   AND PRIOR DBMS_RANDOM.VALUE IS NOT NULL;
   
-- Sinonimo para utilizar fora do DW
   
CREATE PUBLIC SYNONYM NAGV_BASE_CGO_FINALIDADE FOR NAGV_BASE_CGO_FINALIDADE@CONSINCODW;

SELECT * FROM NAGV_BASE_CGO_FINALIDADE
   
SELECT * FROM MFL_DOCTOFISCAL AA WHERE EXISTS (SELECT 1 FROM NAGV_BASE_CGO_FINALIDADE PD WHERE PD.TIPO = 'V' AND PD.CGO_LIST = AA.CODGERALOPER);
