CREATE OR REPLACE VIEW NAGV_CUPONSIDENTIFICADOS_v2 AS

SELECT LOJA, OPERADOR, NOME, DATA, 
       SUM(TOTAL_CUPONS) TOTAL_CUPONS, SUM(TOTAL_CUPONS_IDENTIFICADOS) TOTAL_CUPONS_IDENTIFICADOS,
       SUM(VALOR_TOTAL_CUPONS) VALOR_TOTAL_CUPONS,
       SUM(VALOR_TOTAL_CUPONS_IDENTIFICADOS) VALOR_TOTAL_CUPONS_IDENTIFICADOS
       
  FROM (

SELECT X.NROEMPRESA LOJA,
           X.SEQOPERADOR OPERADOR,
           NVL(Z.NOME,K.NOME) NOME,
           X.DTAMOVIMENTO DATA,
           COUNT(DISTINCT X.SEQDOCTO) TOTAL_CUPONS,
           COUNT(DISTINCT W.SEQDOCTO) TOTAL_CUPONS_IDENTIFICADOS,
           ROUND(SUM(X.VLRTOTDOCTO) - SUM(X.VLRTOTDESCDOCTO),2) VALOR_TOTAL_CUPONS,
           ROUND(SUM(W.VLRTOTDOCTO),2) VALOR_TOTAL_CUPONS_IDENTIFICADOS
 FROM CONSINCO.PDV_DOCTO X  LEFT JOIN CONSINCO.PDV_DESCONTO W ON (X.SEQDOCTO = W.SEQDOCTO)
                                                     LEFT JOIN CONSINCO.FI_TSOPERADORCAIXA Z ON (Z.CODOPERADOR = X.SEQOPERADOR AND Z.NROEMPRESA = X.NROEMPRESA) -- OPERADORES PDV NORMAL
                                                     LEFT JOIN CONSINCO.GE_USUARIO K ON (K.SEQUSUARIO = X.SEQOPERADOR) -- OPERADORES GZ (LOJA 51)
WHERE 1=1
  AND X.TIPODOCTO = 'CF'
  AND X.STATUSDOCTO = 'V'
  GROUP BY X.NROEMPRESA,
           X.SEQOPERADOR,  Z.NOME,K.NOME,
           X.DTAMOVIMENTO
           
           UNION ALL
           
SELECT
    DOC.NROEMPRESA LOJA,
    USU.SEQUSUARIO OPERADOR,
    USU.NOME,
    DOC.DTAMOVIMENTO DATA,

    /* QTDE CUPONS */
    SUM(
        (SELECT COUNT(*)
           FROM MONITORPDV.TB_DOCTOCUPOM CP
          WHERE CP.NROEMPRESA = DOC.NROEMPRESA
            AND CP.NROCHECKOUT = DOC.NROCHECKOUT
            AND CP.SEQDOCTO = DOC.SEQDOCTO
            AND CP.STATUS = 'V')
    ) AS TOTAL_CUPONS,

    /* QTDE CUPONS CPFs */
    SUM(
        (SELECT COUNT(*)
           FROM MONITORPDV.TB_DOCTOPESSOA DP
          WHERE DP.NROEMPRESA = DOC.NROEMPRESA
            AND DP.NROCHECKOUT = DOC.NROCHECKOUT
            AND DP.SEQDOCTO = DOC.SEQDOCTO
            AND DP.CNPJCPF IS NOT NULL
            AND DP.SEQDESTINO = 700)
    ) AS TOTAL_CUPONS_IDENTIFICADOS,

    /* TOTAL PAGAMENTOS (TODOS) */
    SUM(
        (SELECT NVL(SUM(PAG.VLRTOTAL),0)
           FROM MONITORPDV.TB_DOCTOPAGTO PAG
          WHERE PAG.NROEMPRESA = DOC.NROEMPRESA
            AND PAG.NROCHECKOUT = DOC.NROCHECKOUT
            AND PAG.SEQDOCTO = DOC.SEQDOCTO
            AND TRUNC(PAG.DTAHOREMISSAO) = DOC.DTAMOVIMENTO
            AND PAG.STATUS = 'P')
    ) AS VALOR_TOTAL_CUPONS,

    /* TOTAL PAGAMENTOS APENAS DE CUPONS COM CPF */
    SUM(
        (SELECT NVL(SUM(PAG2.VLRTOTAL), 0)
           FROM MONITORPDV.TB_DOCTOPAGTO PAG2
          WHERE PAG2.NROEMPRESA = DOC.NROEMPRESA
            AND PAG2.NROCHECKOUT  = DOC.NROCHECKOUT
            AND PAG2.SEQDOCTO     = DOC.SEQDOCTO
            AND TRUNC(PAG2.DTAHOREMISSAO) = DOC.DTAMOVIMENTO
            AND PAG2.STATUS = 'P'
            AND EXISTS (SELECT 1
                          FROM MONITORPDV.TB_DOCTOPESSOA DP2
                         WHERE DP2.NROEMPRESA = DOC.NROEMPRESA
                           AND DP2.NROCHECKOUT = DOC.NROCHECKOUT
                           AND DP2.SEQDOCTO = DOC.SEQDOCTO
                           AND DP2.CNPJCPF IS NOT NULL)
        )
    ) AS VALOR_TOTAL_CUPONS_IDENTIFICADOS

FROM MONITORPDV.TB_DOCTO DOC
JOIN MONITORPDV.TB_USUARIO USU
  ON USU.SEQUSUARIO = DOC.SEQUSUARIO

WHERE DOC.ESPECIE ='CF'

GROUP BY
    DOC.NROEMPRESA,
    USU.SEQUSUARIO,
    USU.NOME,
    DOC.DTAMOVIMENTO)
    
    GROUP BY LOJA, OPERADOR, NOME, DATA
;
