CREATE OR REPLACE VIEW NAGV_BASE_MRL_PROMOCESPECIAL_APP AS
SELECT (SELECT MAX(C.SEQPROMOCESPECIAL) FROM MRL_PROMOCESPECIALHIST C) + + ROWNUM + 1000000 SEQPROMOCESPECIAL,
       PLU,
       1 QTDEMBALAGEM,
       LOJA NROEMPRESA,
       NULL CODACESSOESPECIAL, --(SELECT NAG_GERA_EAN13_AUTO(LOJA) AS EAN FROM DUAL) CODACESSOESPECIAL,
       ROUND(TRUNC(S.PRECOVALIDNORMAL * 0.9, 1) + 0.09, 2) VLRPRECOPROMOC, -- Tira 10% e arredonda final para 9 (xx.x9)
       QTDE_REBAIXA QTDESOLICITADA,
       0 QTDEETIQEMITIDA,
       DATA_ATIVIDADE DTAINICIO,
       DATA_VALIDADE DTAFIM,
       'P' STATUS,
       'IMPORTACAO APP GERENTES' MOTIVOACAOPROMOC,
       DATA_ATIVIDADE DTAHORALTERACAO,
       'AUTOMATICO' USUALTERACAO,
       NULL DTAHORAPROVACAO,
       NULL USUAPROVACAO,
       NULL MOTIVOREPROVA,
       NULL INDLIBERACAO,
       NULL USULIBERACAO,
       NULL DTAHORALIBERACAO,
       NULL INDEMIETIQUETA,
       NULL SEQPROMOCESPECIALORIGEM,
       NULL INDREPLICAFAMILIA,
       NULL INDREPLICAASSOCIADO,
       NULL INDREPLICARELACIONADO

       FROM NAGV_APP_DATAVALIDADE@CONSINCODW A  INNER JOIN MAX_EMPRESA M ON M.NROEMPRESA = A.LOJA
                                                INNER JOIN MRL_PRODEMPSEG S ON S.SEQPRODUTO = A.PLU AND S.NROEMPRESA = M.NROEMPRESA AND S.NROSEGMENTO = M.NROSEGMENTOPRINC AND S.QTDEMBALAGEM = 1

 WHERE 1=1

   AND DATA_ATIVIDADE = TRUNC(SYSDATE)
   AND QTDE_REBAIXA >= 0
;
