CREATE OR REPLACE VIEW NAGV_APURACAO_SELLOUT_VALIDADE AS
SELECT /*+OPTIMIZER_FEATURES_ENABLE('11.2.0.4')*/
       MAX(A.QTDESOLICITADA)     QTD_SOLIC,
       NVL(SUM(XI.QUANTIDADE),0) QTD_VENDIDA,
       MAX(DTAFIM)               DTA_VENCTO,
       X.NROEMPRESA, XI.SEQPRODUTO
  FROM MFL_DOCTOFISCAL X INNER JOIN MFL_DFITEM XI ON XI.SEQNF = X.SEQNF
                         INNER JOIN MRL_PROMOCESPECIALHIST A ON XI.SEQPRODUTO = A.SEQPRODUTO
                                                         AND TRUNC(SYSDATE) BETWEEN DTAINICIO AND DTAFIM
                                                         AND X.NROEMPRESA = A.NROEMPRESA
                                                         AND X.DTAMOVIMENTO BETWEEN DTAINICIO AND DTAFIM
                                                         AND A.CODACESSOESPECIAL = XI.CODPRODUTO

 WHERE 1=1 
 GROUP BY X.NROEMPRESA, XI.SEQPRODUTO;
