CREATE OR REPLACE VIEW CONSINCO.NAGV_PRODWMS AS

SELECT A.NROEMPRESA DEPOSITANTE,
       A.SEQPRODUTO PLU,
       A.DESCCOMPLETA DESCRICAO,
       A.DESCREDUZIDA,
       A.REFFABRICANTE,
       A.SEQFORNECEDOR COD_FORNEC,
       X.NOMERAZAO FORNEC,
       A.ADVARMAZENAGEM,
       A.QTDTOLARMAZPROD,
       A.PZOVALIDADEDIA,
       DECODE(A.CODTIPENDERECO, 'A',' ALTO','B','BAIXO','M','MEDIO','N','NORMAL') TIPENDERECO,
       AM.DESCRICAO ARMAZENAGEM,
       DECODE(A.TIPSEPARACAO, 'N','NORMAL','C','CONGELADO','F','FLV','L','LEVE','P','PERIGOSO') TIPSEPARACAO,
       M.EMBALAGEM||' - '||A.PADRAOEMBCOMPRA PADRAOEMBCOMPRA,
       V.EMBALAGEM||' - '||A.PADRAOEMBVENDA PADRAOEMBVENDA,
       DECODE(A.STATUSCOMPRA, 'A','ATIVO','I','INATIVO','S','SUSPENSO') STATUSCOMPRA,
       DECODE(A.STATUSVENDA, 'A','ATIVO','I','INATIVO') STATUSVENDA,
       A.EMTETIQUETA,
       A.PESAVEL,
       A.INDPROCFABRICACAO,
       A.SEQPRODUTOBASE PLU_BASE,
       A.QTDVOLGERAETQMASTER
       
  FROM MLO_PRODUTO A  LEFT JOIN GE_PESSOA X ON X.SEQPESSOA = A.SEQFORNECEDOR
                      LEFT JOIN MLO_ATRIBUTOFIXO AM ON AM.LISTA = A.TIPARMAZENAGEM AND AM.TIPATRIBUTOFIXO = 'TIPARMAZ'
                     INNER JOIN MLO_PRODEMBALAGEM M ON M.SEQPRODUTO = A.SEQPRODUTO AND M.NROEMPRESA = A.NROEMPRESA AND M.QTDEMBALAGEM = A.PADRAOEMBCOMPRA
                     INNER JOIN MLO_PRODEMBALAGEM V ON V.SEQPRODUTO = A.SEQPRODUTO AND V.NROEMPRESA = A.NROEMPRESA AND V.QTDEMBALAGEM = A.PADRAOEMBVENDA
                     
 WHERE A.NROEMPRESA > 500
