CREATE OR REPLACE VIEW CONSINCO.NAGV_ECOMM_BASERELAC AS

-- Silene | Ecomm | Alt Integracao

SELECT X.SEQPRODUTO, X.DESCCOMPLETA, NVL(DECODE(X.INDINTEGRAECOMMERCE, 'S','SIM','N','NÃO'),'NÃO') INTEGRA_ECOMM,
                                     DECODE(PESAVEL, 'S','SIM','N','NAO') PESAVEL
  FROM MAP_PRODUTO X INNER JOIN MAP_FAMILIA Z ON X.SEQFAMILIA = Z.SEQFAMILIA
                     
 WHERE X.DESCCOMPLETA LIKE '%CARN%PRAT%'  
