CREATE OR REPLACE VIEW NAGV_EMP_ECOMMERCE AS

SELECT DISTINCT NROEMPRESA, G.NROSEGMENTO
  FROM MAX_EMPRESASEG G INNER JOIN MON_SEGMENTO E ON E.NROSEGMENTO = G.NROSEGMENTO
 WHERE G.STATUS = 'A'
   AND (E.SEGMENTO LIKE 'E-COM%')
