CREATE OR REPLACE VIEW NAGV_BUSCA_CCT_CENARIO_BASE_PROD AS
SELECT C.SEQCENARIO CENARIO, PD.SEQPRODUTO PLU, PD.DESCCOMPLETA, PD.SEQFAMILIA COD_FAMILIA, CI.IDENTIFICADOR IDENT_CCT,
      (SELECT LISTAGG(CODGERALOPER, ', ') WITHIN GROUP (ORDER BY CODGERALOPER) FROM MAX_CODGERALOPER CGO WHERE CGO.CODGERALOPER = CI.VALOR AND CI.IDENTIFICADOR = 'CGO') CGO,
      F.CODNBMSH NCM

  FROM CCT_CENARIO C INNER JOIN CCT_CENARIOCONDICAOITEM CI ON CI.SEQCENARIO = C.SEQCENARIO
                     INNER JOIN CCT_CENARIOIMPOSTO I ON I.SEQCENARIO = C.SEQCENARIO
                      LEFT JOIN MAP_FAMILIA F ON ((CI.IDENTIFICADOR = 'NCM' AND CI.VALOR = TO_CHAR(F.CODNBMSH))
                                              OR  (CI.IDENTIFICADOR = 'FAMILIA' AND CI.VALOR = TO_CHAR(F.SEQFAMILIA)))
                      LEFT JOIN MAP_PRODUTO H ON H.SEQPRODUTO = CI.VALOR AND CI.IDENTIFICADOR = 'PRODUTO'
                     INNER JOIN MAP_PRODUTO PD ON PD.SEQPRODUTO = CI.VALOR AND CI.IDENTIFICADOR = 'PRODUTO' OR PD.SEQFAMILIA = F.SEQFAMILIA AND CI.IDENTIFICADOR IN ('NCM','FAMILIA')
                     --INNER JOIN NAGV_BUSCA_CCT X ON 1=1 AND X.SEQPRODUTO = PD.SEQPRODUTO

 WHERE 1=1
;
