CREATE OR REPLACE VIEW NAGV_APURACAO_CAT28 AS
SELECT DISTINCT A.SEQPRODUTO||';'||NVL(NULLIF(Z.PERALIQUOTA,0), CASE WHEN UF = 'SP' THEN XI.PERALIQUOTAICMSSTDISTRIB END)||';'||NVL(Y.PERALIQUOTA, CASE WHEN UF != 'SP' THEN XI.PERALIQUOTAICMSSTDISTRIB END) LINHA_ARQ, P.DESCCOMPLETA, CO.QTDESTQLOJA, E.NROEMPRESA LJ

  FROM NAGT_BASE_PRODST A INNER JOIN MRL_PRODUTOEMPRESA E ON E.SEQPRODUTO = A.SEQPRODUTO
                          INNER JOIN MLF_NOTAFISCAL X     ON X.SEQNF = E.SEQNFULTENTRCUSTO
                          INNER JOIN MLF_NFITEM XI        ON XI.SEQNF = X.SEQNF AND XI.SEQPRODUTO = A.SEQPRODUTO
                          INNER JOIN GE_PESSOA G          ON G.SEQPESSOA = X.SEQPESSOA
                          INNER JOIN MAP_PRODUTO P        ON P.SEQPRODUTO = A.SEQPRODUTO
                          INNER JOIN MAP_FAMDIVISAO F     ON F.SEQFAMILIA = P.SEQFAMILIA
                          INNER JOIN NAGT_DEPARA_TRIBUT_ST B ON B.TRIBNOVA = F.NROTRIBUTACAO
                          INNER JOIN MAF_FORNECEDOR FF    ON FF.SEQFORNECEDOR = X.SEQPESSOA
                          INNER JOIN MAF_FORNECDIVISAO FD ON FD.SEQFORNECEDOR = FF.SEQFORNECEDOR
                           LEFT JOIN FATO_ESTOQUE CO      ON CO.SEQPRODUTO = A.SEQPRODUTO AND CO.NROEMPRESA = E.NROEMPRESA AND CO.DTAESTOQUE = DATE '2025-12-31'
                          /* LEFT JOIN MAP_TRIBUTACAOUF Y   ON Y.NROTRIBUTACAO = B.TRIBANTIGA AND Y.NROREGTRIBUTACAO = FD.NROREGTRIBUTACAO AND Y.UFCLIENTEFORNEC = G.UF AND Y.UFEMPRESA = 'SP' AND Y.TIPTRIBUTACAO = DECODE(FF.TIPFORNECEDOR, 'I','EI','D','ED') AND UFCLIENTEFORNEC != UFEMPRESA
                          INNER JOIN MAP_TRIBUTACAOUF Z   ON Z.NROTRIBUTACAO = B.TRIBANTIGA AND Z.NROREGTRIBUTACAO = FD.NROREGTRIBUTACAO AND Z.UFCLIENTEFORNEC = 'SP' AND Z.UFEMPRESA = 'SP' AND Z.TIPTRIBUTACAO = DECODE(FF.TIPFORNECEDOR, 'I','EI','D','ED')
                         */
                           LEFT JOIN MAP_TRIBUTACAOUF Y   ON Y.NROTRIBUTACAO = B.TRIBANTIGA AND Y.NROREGTRIBUTACAO = FD.NROREGTRIBUTACAO AND Y.UFCLIENTEFORNEC = G.UF AND Y.UFEMPRESA = 'SP' AND Y.TIPTRIBUTACAO = DECODE(NVL(TIPFORITEM, 'D'), 'D', 'ED','EI') AND UFCLIENTEFORNEC != UFEMPRESA
                          INNER JOIN MAP_TRIBUTACAOUF Z   ON Z.NROTRIBUTACAO = B.TRIBANTIGA AND Z.NROREGTRIBUTACAO = FD.NROREGTRIBUTACAO AND Z.UFCLIENTEFORNEC = 'SP' AND Z.UFEMPRESA = 'SP' AND Z.TIPTRIBUTACAO = DECODE(NVL(TIPFORITEM, 'D'), 'D', 'ED','EI')
                          
 WHERE 1=1 AND (NVL(NULLIF(Z.PERALIQUOTA,0), CASE WHEN UF = 'SP' THEN XI.PERALIQUOTAICMSSTDISTRIB END) > 0 OR NVL(Y.PERALIQUOTA, CASE WHEN UF != 'SP' THEN XI.PERALIQUOTAICMSSTDISTRIB END) > 0);-- AND A.SEQPRODUTO = 335195;
 
