CREATE OR REPLACE VIEW NAGV_NOTAABERTA_IMP AS

SELECT 'R$ '||TO_CHAR(SUM(XI.VLRICMS), 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') ICMS, 
       'R$ '||TO_CHAR(SUM(XI.VLRPIS), 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') PIS, 
       'R$ '||TO_CHAR(SUM(XI.VLRCOFINS), 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') COFINS,
       'R$ '||TO_CHAR(SUM(X.VLRAFRMM), 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') AFRMM, 
       'R$ '||TO_CHAR(SUM(XI.VLRIMPOSTOIMPORT), 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') II, 
       'R$ '||TO_CHAR(SUM(XI.VLRDESPTRIBUTITEM), 'FM999G999G990D90', 'NLS_NUMERIC_CHARACTERS='',.''') OUTRAS, 
       
       NRODECLARAIMPORT
       
  FROM MLF_NOTAFISCAL X INNER JOIN MLF_NFITEM XI ON XI.SEQNF = X.SEQNF

 WHERE X.NRODECLARAIMPORT IS NOT NULL

   AND X.CODGERALOPER IN (5,44)
   AND X.STATUSNF = 'V'

   GROUP BY NRODECLARAIMPORT;
