CREATE OR REPLACE VIEW NAGV_ITWORKS_REINF_INSS AS

SELECT NROEMPRESA LOJA, NRONOTA NF, X.DTAEMISSAO EMISSAO, X.DTAENTRADA LANCAMENTO, X.SERIE, D.DESCRICAO CODIGO_SERVICO, D.REINF CODIGO_REINF, 
       G.NOMERAZAO RAZAO_SOCIAL, ALIQINSS, X.VALOR VALOR_BRUTO, X.VLRBASEINSS BASECALC, X.VLRINSS
       
  FROM OR_NFDESPESA X  LEFT JOIN NAGT_DEPARA_INSS D ON D.COD_NAT = TO_CHAR(X.CODHISTORICO)
                      INNER JOIN GE_PESSOA G ON G.SEQPESSOA = X.SEQPESSOA
                      
 WHERE X.SITUACAO = 'I' AND  NVL(VLRINSS,0) > 0;
 
