CREATE OR REPLACE VIEW NAGV_SAIDAS AS
SELECT /*+OPTIMIZER_FEATURES_ENABLE('11.2.0.4')*/
       XX.DTAMOVIMENTO PERIODO,
       XX.NFECHAVEACESSO CHAVE,
       DECODE(XX.STATUSDF, 'V', 'Autorizado', 'C', 'Cancelado') SITUACAO,
       XX.SERIEDF SERIE,
       XX.NUMERODF NUMERO_DOC,
       TO_DATE(XX.DTAHOREMISSAO, 'DD/MM/RRRR') DTAEMISSAO,
       XX.NROCHECKOUT NRO_CAIXA,
       LPAD(G.NROCGCCPF,12,0)||LPAD(G.DIGCGCCPF,2,0) CNPJ_EMITENTE,
       G.NOMERAZAO     NOME_EMITENTE,
       XI.SEQITEMDF    NUMERO_ITEM,
       XI.SEQPRODUTO   CODIGO_ITEM,
       P.DESCCOMPLETA  DESC_ITEM,
       XI.CODPRODUTO   COD_BARRA,
       F.CODNBMSH      NCM,
       XI.CODCEST      CEST,
       XI.CFOP         CFOP,
       XI.QTDEMBALAGEM UNIDADE_MEDIDA,
       XI.QUANTIDADE   QTDE,
       ROUND((XI.VLRITEM - XI.VLRDESCONTO) / XI.QUANTIDADE,2) VLR_UNITARIO,
       ROUND(XI.VLRITEM,2) VLR_BRUTO_PROD,
       ROUND(XI.VLRDESCONTO,2) VLR_DESCONTO,
       NVL(XI.VLRDESPOPERACIONAL,0) + NVL(XI.VLRTOTDESPACESSORIA,0) + NVL(XI.VLRDESPTRIBUTITEM,0) + NVL(XI.VLRDESPNTRIBUTITEM,0) VLR_OUT_DESP,
       ROUND((XI.VLRITEM - XI.VLRDESCONTO),2) VLR_LIQ_ITEM,
       ROUND(XI.VLRDESCONTO,2) RATEIO_DESCONTO,
       ROUND(XI.VLRACRESCIMO,2) RATEIO_ACRESCIMO,
       SUBSTR(XI.SITUACAONF,0,1) ORIGEM_ICMS,
       SUBSTR(XI.SITUACAONF,2,2) CST_ICMS,
       XI.BASCALCICMS VLR_BASE_CALC_ICMS,
       XI.PERALIQUOTAICMS ALIQUOTA_ICMS,
       XI.VLRICMS VLR_ICMS,
       XI.SITUACAONFPIS CST_PIS,
       XI.BASCALCPIS VLR_BASE_CALC_PIS,
       XI.PERALIQUOTAPIS ALIQ_PIS,
       XI.VLRPIS VLR_PIS,
       XI.SITUACAONFCOFINS CST_COFINS,
       XI.BASCALCOFINS VLR_BASE_CALC_COFINS,
       XI.PERALIQUOTACOFINS ALIQ_COFINS,
       XI.VLRCOFINS VLR_COFINS,
       XI.VLRICMS VLR_TOTAL_ICMS,
       ROUND((XI.VLRITEM - XI.VLRDESCONTO),2) VLR_TOTAL_PRODUTOS,
       ROUND(XI.VLRDESCONTO) VLR_TOTAL_DESCONTO,
       XI.VLRPIS VLR_TOTAL_PIS,
       XI.VLRCOFINS VLR_TOTAL_COFINS,
       NVL(XI.VLRDESPOPERACIONAL,0) + NVL(XI.VLRTOTDESPACESSORIA,0) + NVL(XI.VLRDESPTRIBUTITEM,0) + NVL(XI.VLRDESPNTRIBUTITEM,0) VLR_TOTAL_OUT_DESP,
       ROUND(XI.VLRDESCONTO,2) VLR_DESC_SUBTOTAL,
       ROUND(XI.VLRACRESCIMO,2) VLR_ACRESCIMO_SUBTOTAL,
       REPLACE(REPLACE(REPLACE(SUBSTR(XX.OBSERVACAO,0,200), CHR(10), ' '), CHR(13), ' '), ';',' ') INFO_COMPLEMENTAR,
       XX.NROEMPRESA, XI.VLRIPI, XX.ROWID ID, 'D' TP, XI.VLRICMSST, XI.SITUACAONFIPI


  FROM MFL_DOCTOFISCAL XX INNER JOIN MAX_EMPRESA E ON E.NROEMPRESA = XX.NROEMPRESA
                          INNER JOIN MFL_DFITEM XI ON XX.SEQNF = XI.SEQNF
                          INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = XI.SEQPRODUTO
                          INNER JOIN GE_PESSOA G   ON G.SEQPESSOA = XX.NROEMPRESA
                          INNER JOIN MAP_FAMILIA F ON F.SEQFAMILIA = P.SEQFAMILIA
 WHERE 1=1
   AND XX.STATUSDF = 'V'
   AND XI.STATUSITEM = 'V'
   AND XI.VLRITEM > 0 AND QUANTIDADE > 0
/*      AND XX.CODGERALOPER NOT IN (SELECT CODGERALOPER from MAX_CODGERALOPER t WHERE TIPCGO = 'S' AND TIPUSO = 'E' AND TIPDOCFISCAL = 'O')
*/

   --AND XX.CODGERALOPER IN (37,48,123,610,615,613,810,916,910,911,76)
   --AND XX.SERIEDF = 'CF';
   --AND EXISTS (SELECT 1 FROM NAGT_XML_EXTRAIDO X WHERE X.DESCRICAONF NOT LIKE '%Ent%' AND DESCRICAONF NOT LIKE '%Orc%' AND TO_CHAR(X.CHAVENFE) = TO_CHAR(XX.NFECHAVEACESSO))

UNION

SELECT /*+OPTIMIZER_FEATURES_ENABLE('11.2.0.4')*/
       XX.DTAEMISSAO PERIODO,
       XX.NFECHAVEACESSO CHAVE,
       DECODE(XX.STATUSNF, 'V', 'Autorizado', 'C', 'Cancelado') SITUACAO,
       XX.SERIENF SERIE,
       XX.NUMERONF NUMERO_DOC,
       TO_DATE(XX.DTAEMISSAO, 'DD/MM/RRRR') DTAEMISSAO,
       NULL NRO_CAIXA,
       LPAD(G.NROCGCCPF,12,0)||LPAD(G.DIGCGCCPF,2,0) CNPJ_EMITENTE,
       G.NOMERAZAO     NOME_EMITENTE,
       XI.SEQITEMNF    NUMERO_ITEM,
       XI.SEQPRODUTO   CODIGO_ITEM,
       P.DESCCOMPLETA  DESC_ITEM,
       TO_CHAR(XI.SEQPRODUTO)   COD_BARRA,
       F.CODNBMSH      NCM,
       XI.CODCEST      CEST,
       XI.CFOP         CFOP,
       XI.QTDEMBALAGEM UNIDADE_MEDIDA,
       XI.QUANTIDADE   QTDE,
       ROUND((XI.VLRITEM - XI.VLRDESCITEM) / XI.QUANTIDADE,2) VLR_UNITARIO,
       ROUND(XI.VLRITEM,2) VLR_BRUTO_PROD,
       ROUND(XI.VLRDESCITEM,2) VLR_DESCONTO,
       XI.VLRDESPTRIBUTITEM+
       XI.VLRDESPNTRIBUTITEM+
       XI.VLRDESPFORANF+
       XI.VLRDESPICMS+
       XI.VLRDESPTRIBFORA+
       XI.VLRDESPFIXAFORN+
       XI.VLRDESPOPERACIONALITEM+
       XI.VLRDESPESAAD+
       XI.VLRDESPFORANFSEMINCID+
       XI.VLRDESPESARATEIODANFE VLR_OUT_DESP,
       ROUND((XI.VLRITEM - XI.VLRDESCITEM),2) VLR_LIQ_ITEM,
       ROUND(XI.VLRDESCITEM,2) RATEIO_DESCONTO,
       ROUND(XI.VLRACRESCIMO,2) RATEIO_ACRESCIMO,
       SUBSTR(XI.SITUACAONF,0,1) ORIGEM_ICMS,
       SUBSTR(XI.SITUACAONF,2,2) CST_ICMS,
       XI.BASCALCICMS VLR_BASE_CALC_ICMS,
       XI.PERALIQUOTAICMS ALIQUOTA_ICMS,
       XI.VLRICMS VLR_ICMS,
       XI.SITUACAONFPIS CST_PIS,
       XI.BASCALCPIS VLR_BASE_CALC_PIS,
       XI.PERALIQUOTAPIS ALIQ_PIS,
       XI.VLRPIS VLR_PIS,
       NVL(XI.SITUACAONFCOFINS, Xi.Sitpiscofinssimples) CST_COFINS,
       XI.BASCALCOFINS VLR_BASE_CALC_COFINS,
       XI.PERALIQUOTACOFINS ALIQ_COFINS,
       XI.VLRCOFINS VLR_COFINS,
       XI.VLRICMS VLR_TOTAL_ICMS,
       ROUND((XI.VLRITEM - XI.VLRDESCITEM),2) VLR_TOTAL_PRODUTOS,
       ROUND(XI.VLRDESCITEM) VLR_TOTAL_DESCONTO,
       XI.VLRPIS VLR_TOTAL_PIS,
       XI.VLRCOFINS VLR_TOTAL_COFINS,
       XI.VLRDESPTRIBUTITEM+
       XI.VLRDESPNTRIBUTITEM+
       XI.VLRDESPFORANF+
       XI.VLRDESPICMS+
       XI.VLRDESPTRIBFORA+
       XI.VLRDESPFIXAFORN+
       XI.VLRDESPOPERACIONALITEM+
       XI.VLRDESPESAAD+
       XI.VLRDESPFORANFSEMINCID+
       XI.VLRDESPESARATEIODANFE VLR_TOTAL_OUT_DESP,
       ROUND(XI.VLRDESCITEM) VLR_DESC_SUBTOTAL,
       XI.VLRACRESCIMO VLR_ACRESCIMO_SUBTOTAL,
       REPLACE(REPLACE(REPLACE(SUBSTR(XX.OBSERVACAO,0,200), CHR(10), ' '), CHR(13), ' '), ';',' ') INFO_COMPLEMENTAR,
       XX.NROEMPRESA, XI.VLRIPI, XX.ROWID ID, 'N' TP , XI.VLRICMSST, XI.SITUACAONFIPI


  FROM MLF_NOTAFISCAL XX INNER JOIN MAX_EMPRESA E ON E.NROEMPRESA = XX.NROEMPRESA
                          INNER JOIN MLF_NFITEM XI ON XX.SEQNF = XI.SEQNF
                          INNER JOIN MAP_PRODUTO P ON P.SEQPRODUTO = XI.SEQPRODUTO
                          INNER JOIN GE_PESSOA G   ON G.SEQPESSOA = XX.NROEMPRESA
                          INNER JOIN MAP_FAMILIA F ON F.SEQFAMILIA = P.SEQFAMILIA
                          INNER JOIN MAX_CODGERALOPER X ON X.CODGERALOPER = XX.CODGERALOPER
 WHERE 1=1
   AND XX.STATUSNF = 'V' AND STATUSNFE = '4'
   AND XI.VLRITEM > 0    AND QUANTIDADE > 0
  -- AND XX.CODGERALOPER NOT IN (37,48,123,610,615,613,810,916,910,911,76)
/*   AND XX.CODGERALOPER NOT IN (SELECT CODGERALOPER from MAX_CODGERALOPER t WHERE TIPCGO = 'S' AND TIPUSO = 'E' AND TIPDOCFISCAL = 'O')
*/   AND XX.SERIENF != 'CF'
   AND (XX.TIPNOTAFISCAL = 'S' OR DESCRICAO LIKE '%EMI%' AND TIPCGO = 'E')
   AND XX.MODELONF IN (55,65)
;
