CREATE OR REPLACE VIEW NAGV_STATUS_EXP_INT_PDV AS
--VALIDA DOCUMENTOS NAO EXPORTADOS
WITH TBDOCTOPENDENTEEXPORTACAO AS
 (SELECT COUNT(1) QTDE
    FROM MONITORPDV.TB_DOCTO
   WHERE DTAMOVIMENTO = TRUNC(SYSDATE)
         AND REPLICACAO IN ('P', 'S')),
TBPACOTEPENDENTEIMPORTACAO AS
 (SELECT COUNT(1) QTDE FROM MONITORPDV.TB_CONTROLEMOVIMENTO WHERE STATUS < 2),
TBSESSOES AS
 (SELECT COUNT(1) QTDE
    FROM V$SESSION A
   WHERE LOWER(A.PROGRAM) LIKE '%acruxmonitorservice%'),
TBDOCTOINTEGRADO AS
 (SELECT COUNT(1) QTDE
    FROM MONITORPDV.TB_DOCTO
   WHERE DTAMOVIMENTO = TRUNC(SYSDATE)),
TBULTCARGAPRECO AS
 (SELECT MAX(A.DTAHORFINAL) DTAHOREMISSAO
    FROM MONITORPDV.TB_LOGCARGAMONITOR A
   WHERE A.TABELA = 'TB_PRODPRECO'),
TBULTDOCTOINTEGRADO AS
 (SELECT MAX(A.DTAHORAMOVTO) DTAHOREXPORTACAO
    FROM MONITORPDV.SY_MFL_CUPOMFISCAL A
   WHERE A.DTAMOVIMENTO >= TRUNC(SYSDATE))
   
SELECT A.QTDE             PENDENTEEXPORTACAO,
       B.QTDE             PENDENTEIMPORTACAO,
       C.QTDE             SESSOES,
       D.QTDE             DOCTOINTEGRADO,
       E.DTAHOREMISSAO    ULTCARGAPRECO,
       F.DTAHOREXPORTACAO
  FROM TBDOCTOPENDENTEEXPORTACAO  A,
       TBPACOTEPENDENTEIMPORTACAO B,
       TBSESSOES                  C,
       TBDOCTOINTEGRADO           D,
       TBULTCARGAPRECO            E,
       TBULTDOCTOINTEGRADO        F;
