CREATE OR REPLACE VIEW NAGV_ITWORKS_REINF_INSS AS

SELECT LPAD(M.NROCGC,12,0)||LPAD(M.DIGCGC,2,0) CNPJ_ENTRADA, 
       LPAD(G.NROCGCCPF,12,0)||LPAD(G.DIGCGCCPF,2,0) CNPJ_PRESTADOR,
       TO_CHAR(DTAEMISSAO, 'MM') MES,
       TO_CHAR(DTAEMISSAO, 'YYYY') ANO,
       X.NROEMPRESA LOJA, NRONOTA NF, X.DTAEMISSAO EMISSAO, X.DTAENTRADA LANCAMENTO, X.SERIE, D.DESCRICAO CODIGO_SERVICO, D.REINF CODIGO_REINF,
       G.NOMERAZAO RAZAO_SOCIAL, ALIQINSS, X.VALOR VALOR_BRUTO, X.VLRBASEINSS BASECALC, X.VLRINSS

  FROM OR_NFDESPESA X  LEFT JOIN NAGT_DEPARA_INSS D ON D.COD_NAT = TO_CHAR(X.CODHISTORICO)
                      INNER JOIN GE_PESSOA G ON G.SEQPESSOA = X.SEQPESSOA
                      INNER JOIN MAX_EMPRESA M ON M.NROEMPRESA = X.NROEMPRESA

 WHERE X.SITUACAO = 'I' AND  NVL(VLRINSS,0) > 0;
