CREATE OR REPLACE VIEW NAGV_BASE_PROMOC_PDV AS
SELECT X.SEQPROMOCPDV, DESCRICAO, X.STATUS, DTAINICIO, DTAFIM, X.DTAALTERACAO, X.USUALTERACAO,
       XI.SEQPRODUTO, XD.PRECOPROMOCAO, XE.NROEMPRESA, XD.QTDAPARTIRDE, XI.QTDEMBALAGEM, X.TIPOPROMOCAO, INDTIPOQTDCARGAPDV, CODPARCEIRO, LPAD(XD.QTDAPARTIRDE,2,0)|| ' UNID.' QTDE
  FROM MFL_PROMOCAOPDV X INNER JOIN MFL_PROMOCPDVITEM XI ON XI.SEQPROMOCPDV = X.SEQPROMOCPDV -- MAPV_APIPROMOCAOAPARTIR
                         INNER JOIN MFL_PROMOCPDVDESCAPARTDE XD ON XD.SEQPROMOCPDV = X.SEQPROMOCPDV AND XD.SEQITEMPROMOC = XI.SEQITEMPROMOC
                         INNER JOIN MFL_PROMOCPDVEMP XE ON XE.SEQPROMOCPDV = X.SEQPROMOCPDV AND XE.NROEMPRESA = XD.NROEMPRESA

WHERE 1=1
  AND X.STATUS  = 'A'
  AND XI.STATUS = 'A'
  AND XE.STATUS = 'A'
  AND TRUNC(SYSDATE) BETWEEN X.DTAINICIO AND X.DTAFIM
;
